starlight: remove apk mirrors from Dockerfile
The ruby 2.6.2-alpine image targets alpine 3.9, while "latest" is now
3.11.

A clean build results in the following due to that gap, presumably:
```
fetch http://mirror.leaseweb.com/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.leaseweb.com/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libffi-3.2.1-r6:
    conflicts: libffi-3.3-r2
    satisfies: libffi-dev-3.2.1-r6[libffi=3.2.1-r6]
               .ruby-rundeps-0[so:libffi.so.6]
  libffi-3.3-r2:
    conflicts: libffi-3.2.1-r6
    breaks: libffi-dev-3.2.1-r6[libffi=3.2.1-r6]
    satisfies: llvm10-libs-10.0.0-r2[so:libffi.so.7]
               glib-2.64.3-r0[so:libffi.so.7]
               p11-kit-0.23.20-r5[so:libffi.so.7]
```