comet: remove apk upgrade from Dockerfile
Unfortunately it looks like the baselayout package and/or the upgrade
script was updated, and we are getting the following errors in build
jobs:

```sh
(4/4) Upgrading alpine-baselayout (3.2.0-r20 -> 3.2.0-r22)
Executing alpine-baselayout-3.2.0-r22.pre-upgrade
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..data': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/token': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/namespace': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2022_06_29_20_41_01.118515204/ca.crt': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2022_06_29_20_41_01.118515204/token': Read-only file system
rm: can't remove '/var/run/secrets/kubernetes.io/serviceaccount/..2022_06_29_20_41_01.118515204/namespace': Read-only file system
ERROR: alpine-baselayout-3.2.0-r22: failed to rename var/.apk.f752bb51c942c7b3b4e0cf24875e21be9cdcd4595d8db384 to var/run.
Executing alpine-baselayout-3.2.0-r22.post-upgrade
```

So, we temporarily remove the `apk upgrade` calls to avoid this.